name: FlutterHomework
description: Google Flutter homeworks

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.17.0
  cupertino_icons: ^1.0.0
  powers: ^0.1.0
  pedantic: any
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
